CREATE DATABASE QuanLyHocSinh;
GO

USE QuanLyHocSinh;
GO

CREATE TABLE Dang_Nhap(
Ma_TK VARCHAR(10) PRIMARY KEY,
Ten_TK VARCHAR(100) UNIQUE NOT NULL,
Mat_Khau VARCHAR(100) NOT NULL,
Loai_TK NVARCHAR(50) NOT NULL CHECK(Loai_TK IN ('Admin','GiaoVien','HocSinh')),

CONSTRAINT CK_QuyTacDatma CHECK (
(Loai_TK = 'Admin' AND Ma_TK LIKE 'AD%') OR
(Loai_TK = 'GiaoVien' AND Ma_TK LIKE 'GV%') OR
(Loai_TK = 'HocSinh' AND Ma_TK like 'HS%')
)
);


CREATE TABLE Mon_Hoc(
Ma_MH VARCHAR(10) PRIMARY KEY,
Ten_MH NVARCHAR(50) NOT NULL
);
 
CREATE TABLE Hoc_Ky(
Ma_HK VARCHAR(10) PRIMARY KEY,
Ten_HK NVARCHAR(50) NOT NULL,
Nam_Hoc VARCHAR(10),
Trang_Thai BIT DEFAULT 1
);

CREATE TABLE Giao_Vien(
Ma_GV VARCHAR(10) PRIMARY KEY,
Ma_MH VARCHAR(10) NOT NULL,
Ten_GV NVARCHAR(50) NOT NULL,
Ngay_Sinh DATE,
Gioi_Tinh NVARCHAR(10) NOT NULL,
Email NVARCHAR(50) NOT NULL,
SDT VARCHAR(10) NOT NULL,
Chuc_Vu NVARCHAR(50) NOT NULL,

FOREIGN KEY (Ma_GV) REFERENCES Dang_Nhap(Ma_TK),
FOREIGN KEY (Ma_MH) REFERENCES Mon_Hoc(Ma_MH)
);

CREATE TABLE Lop (
Ma_Lop VARCHAR(10) PRIMARY KEY,
Ma_GVCN VARCHAR(10) NOT NULL,
Ten_Lop NVARCHAR(50) NOT NULL,
Nam_Hoc VARCHAR(10) NOT NULL,

FOREIGN KEY (Ma_GVCN) REFERENCES Giao_Vien(Ma_GV)
);

CREATE TABLE Hoc_Sinh(
Ma_HS VARCHAR(10) PRIMARY KEY,
Ma_Lop VARCHAR(10) NOT NULL,
Ten_HS NVARCHAR(50) NOT NULL,
Ngay_Sinh DATE NOT NULL,
Gioi_Tinh NVARCHAR(10) NOT NULL,
Email NVARCHAR(50) NOT NULL,
SDT VARCHAR(10) NOT NULL,

FOREIGN KEY(Ma_HS) REFERENCES Dang_Nhap(Ma_TK),
FOREIGN KEY (Ma_Lop) REFERENCES Lop(Ma_Lop)
);

CREATE TABLE Diem(
Ma_MH VARCHAR(10) NOT NULL,
Ma_HS VARCHAR(10) NOT NULL,
Ma_HK VARCHAR(10) NOT NULL,
Diem_Mieng FLOAT,
Diem_15P FLOAT,
Diem_45P FLOAT,
Diem_GK FLOAT,
Diem_CK FLOAT,

Diem_TK AS 
        ROUND(
            (ISNULL(Diem_Mieng,0) * 0.10) +
            (ISNULL(Diem_15P,0)   * 0.10) +
            (ISNULL(Diem_45P,0)   * 0.20) +
            (ISNULL(Diem_GK,0)    * 0.20) +
            (ISNULL(Diem_CK,0)    * 0.40), 2
        ) PERSISTED,
PRIMARY KEY(Ma_MH,Ma_HS,Ma_HK),

FOREIGN KEY(Ma_MH) REFERENCES Mon_Hoc(Ma_MH),
FOREIGN KEY(Ma_HS) REFERENCES Hoc_Sinh(Ma_HS),
FOREIGN KEY(Ma_HK) REFERENCES Hoc_Ky(Ma_HK)
);


CREATE TABLE Phan_Cong(
Ma_PC INT IDENTITY(1,1) PRIMARY KEY,
Ma_GV VARCHAR(10) NOT NULL,
Ma_Lop VARCHAR(10) NOT NULL,
Ma_MH VARCHAR(10) NOT NULL,
Ma_HK VARCHAR(10) NOT NULL,

FOREIGN KEY(Ma_GV) REFERENCES Giao_Vien(Ma_GV),
FOREIGN KEY(Ma_Lop) REFERENCES Lop(Ma_Lop),
FOREIGN KEY(Ma_MH) REFERENCES Mon_Hoc(Ma_MH),
FOREIGN KEY(Ma_HK) REFERENCES Hoc_Ky(Ma_HK),

CONSTRAINT UQ_Phan_Cong UNIQUE (Ma_Lop,Ma_MH,Ma_HK)
);






